### ISSUE TITLE
Invalid patch models paths 

### ISSUE THREAD

**Issue by specblades** [fireicewolf/wd-joy-caption-cli#5]
How to fix this error? Got it with command `python caption.py D:\DATASETS\equals --model_site modelscope --download_method URL --wd_force_use_cpu --wd_remove_underscore --llm_patch`. All the files are downloaded and in place.

```
2024-10-06 16:07:34,573 - inference.py[line:115] - ERROR: Invalid models paths: (WindowsPath('models/Llama-3.2-11B-Vision-Instruct/llm'), WindowsPath('models/Llama-3.2-11B-Vision-Instruct/patch'))!!!
2024-10-06 16:07:34,573 - inference.py[line:115] - ERROR: None
Traceback (most recent call last):
  File "S:\wd-llm-caption-cli\caption.py", line 649, in <module>
    my_caption.load_models(get_args)
  File "S:\wd-llm-caption-cli\caption.py", line 181, in load_models
    self.my_llm = LLM(
  File "S:\wd-llm-caption-cli\utils\inference.py", line 116, in __init__
    raise ValueError
ValueError
```

**Comment by fireicewolf** [comment]
Fixed with commit [9038222](https://github.com/fireicewolf/wd-llm-caption-cli/commit/903822229eeba201435d9f3640514856551b0616)
